name: hosting-unity-webgl
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/unity-webgl-template/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/hosting-unity-webgl-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  hosting-unity-webgl-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Hosting Unity Webgl Darwin
        run: |
          .github/workflows/hosting-unity-webgl-example.test.sh
  hosting-unity-webgl-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Hosting Unity Webgl Linux
        run: |
          .github/workflows/hosting-unity-webgl-example.test.sh
