name: motoko-basic-dao
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/basic_dao/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-basic-dao-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-dao-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko DAO Darwin
        run: |
          .github/workflows/motoko-basic-dao-example.test.sh
  motoko-hello-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko DAO Linux
        run: |
          .github/workflows/motoko-basic-dao-example.test.sh
