name: motoko-classes
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - motoko/composite_query/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-composite-query-example.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  motoko-classes-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Composite Query Darwin
        run: |
          dfx start --background
          pushd motoko/composite_query
          make test
          popd
  motoko-classes-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Composite Query Linux
        run: |
          dfx start --background
          pushd motoko/composite_query
          make test
          popd
