name: rust-face-recognition
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - rust/face-recognition/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-face-recognition-example.yaml
      - .ic-commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rust-face-recognition-example-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: DFX_VERSION="0.23.0" bash .github/workflows/provision-darwin.sh
      - name: Remove networks.json
        run: rm -f ~/.config/dfx/networks.json
      - name: Rust Face Recognition Darwin
        run: |
          dfxvm install 0.22.0-beta.0
          dfx start --backgroud --clean --pocketic
          pushd rust/face-recognition
          npm install
          dfx deploy --yes 
          popd
  rust-face-recognition-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: DFX_VERSION="0.23.0" bash .github/workflows/provision-linux.sh
      - name: Remove networks.json
        run: rm -f ~/.config/dfx/networks.json
      - name: Rust Face Recognition Linux
        run: |
          dfxvm install 0.22.0-beta.0
          dfx start --backgroud --clean --pocketic
          pushd rust/face-recognition
          npm install
          dfx deploy --yes 
          popd
